substitutions:
  _REGISTRY: cr.yandex/<registry-id>
  _IMAGE: ${_REGISTRY}/telegram-ai-bot
  _DEPLOY_SPEC: deploy-spec.yaml
  _DEPLOY_SA: <deploy-service-account-id>

steps:
  - name: python
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        pip install python-dotenv pytest
        python predeploy_check.py --env .env --env .env.prod
        pytest -q tests/test_smoke.py

  - name: docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build -t ${_IMAGE}:$BUILD_ID .
        docker push ${_IMAGE}:$BUILD_ID

  - name: yc
    entrypoint: bash
    args:
      - -c
      - |
        yc deploy release run \
          --spec ${_DEPLOY_SPEC} \
          --service-account-id ${_DEPLOY_SA} \
          --labels build_id=$BUILD_ID \
          --description "Auto deploy $BUILD_ID"

timeout: 1200s
